package lt.viko.eif.bondarenko.producer.entety;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Entity representing an item in the shop.
 * This class maps to the "items" table in the database.
 */
@Data
@Entity
@Table(name = "items")
@AllArgsConstructor
@NoArgsConstructor
public class Item {

    /**
     * Unique identifier for the item.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the item.
     */
    private String name;

    /**
     * Price of the item.
     */
    private BigDecimal price;

    /**
     * Description of the item.
     */
    private String description;

    /**
     * Constructor used when only the ID is needed (e.g., for references).
     *
     * @param id the item's ID
     */
    public Item(Long id) {
        this.id = id;
    }

    /**
     * Constructor used to create a new item without specifying an ID.
     *
     * @param name the item's name
     * @param price the item's price
     * @param description the item's description
     */
    public Item(String name, BigDecimal price, String description) {
        this.name = name;
        this.price = price;
        this.description = description;
    }
}
