package lt.viko.eif.bondarenko.producer.entety;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Entity representing a customer's order.
 * This class maps to the "orders" table in the database.
 */
@Data
@Entity
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "orders")
public class Order {

    /**
     * Unique identifier for the order.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the customer who placed the order.
     */
    @Column(name = "customer_name")
    private String customerName;

    /**
     * Date the order is scheduled for delivery.
     */
    @Column(name = "delivery_date")
    private LocalDate deliveryDate;

    /**
     * Address where the order should be delivered.
     */
    @Column(name = "delivery_address")
    private String deliveryAddress;

    /**
     * List of items included in the order.
     * Uses cascading to persist order items along with the order,
     * and removes orphaned items when deleted from the list.
     */
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItem> items;

    /**
     * Total price of all items in the order.
     */
    @Column(name = "total_price")
    private BigDecimal totalPrice;
}

