package lt.viko.eif.bondarenko.producer.entety;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * Entity representing an item within a specific order.
 * Maps to the "order_items" table in the database.
 */
@Data
@NoArgsConstructor
@Entity
@Table(name = "order_items")
public class OrderItem {

    /**
     * Unique identifier for the order item.
     * This value is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Reference to the {@link Item} being ordered.
     * This relationship is many-to-one, meaning multiple OrderItem entries can reference the same Item.
     */
    @ManyToOne
    @JoinColumn(name = "item_id", nullable = false)
    private Item item;

    /**
     * Quantity of the item included in the order.
     */
    private long quantity;

    /**
     * Convenience constructor for creating an OrderItem by item ID and quantity.
     * Internally constructs a lightweight {@link Item} reference using the provided ID.
     *
     * @param itemId   ID of the item
     * @param quantity quantity of the item in the order
     */
    public OrderItem(long itemId, long quantity) {
        this.item = new Item(itemId);
        this.quantity = quantity;
    }
}

